import React from 'react';
import { it, expect, vi } from 'vitest';
import { render, screen, fireEvent, waitFor } from '@testing-library/react';
import App from './App';
import newsApi from './features/news/api/newsApi';
vi.mock('./features/news/api/newsApi', () => ({ default: { search: vi.fn() } }));
vi.mock('./features/ai/api/aiApi', () => ({ default: { status: vi.fn().mockResolvedValue({ enabled: false }) } }));
it('associates mobile tabs with the active panel and supports keyboard navigation', async () => {
  window.matchMedia.mockImplementation(query => ({ matches: query.includes('720px'), media: query, addEventListener: vi.fn(), removeEventListener: vi.fn() }));
  newsApi.search.mockResolvedValue({ articles: [], page: 1 });
  render(<App />);
  const discover = screen.getByRole('tab', { name: /Discover/ });
  const ai = screen.getByRole('tab', { name: /AI workspace/ });
  fireEvent.keyDown(discover, { key: 'ArrowRight' });
  expect(ai).toHaveFocus(); expect(ai).toHaveAttribute('aria-selected', 'true');
  expect(screen.getByRole('tabpanel')).toHaveAttribute('aria-labelledby', 'tab-ai');
  fireEvent.keyDown(ai, { key: 'Home' });
  expect(discover).toHaveFocus(); expect(ai).toHaveAttribute('tabindex', '-1');
  await waitFor(() => expect(newsApi.search).toHaveBeenCalled());
});
